### ISSUE TITLE
Clicking info card on mobile doesn't remove border after click

### ISSUE THREAD

**Issue by sklirg** [dotkom/supreme-guacamole#90]
![screenshot_20170823-102628](https://user-images.githubusercontent.com/5422571/29606490-c1940bb2-87ee-11e7-81ae-5026a56d5c45.png)

![screenshot_20170823-102624](https://user-images.githubusercontent.com/5422571/29606454-a7d334c8-87ee-11e7-8318-9d39c28a59a6.png)

**Comment by duvholt** [comment]
That's pretty much how hover works on mobile.

I don't think there is a clean fix for this.

**Comment by sklirg** [comment]
Interesting. I guess we'll close this then.
